name: Java Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18'
        
    - name: Build with Maven
      run: mvn -B package --file SAS/pom.xml
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18'
    - name: Run tests
      run: mvn test --file SAS/pom.xml

  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: "sas.com"
    needs: test
    steps: 
      - name: Run a one-line script
        run: echo Deploy Dev

  deploy-hmg:
    runs-on: ubuntu-latest
    environment: 
      name: homologação
      url: 'sas.com'
    needs: deploy-dev
    steps: 
      - name: Run a one-line script
        run: echo Deploy Homologação
  
  deploy-prd:
    runs-on: ubuntu-latest
    environment: 
      name: produção
      url: 'sas.com'
    needs: deploy-hmg
    steps: 
      - name: Run a one-line script
        run: echo Deploy Produção

